services:
  pgdb:
    image: postgres:18
    container_name: pgdb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./database:/var/lib/postgresql:rw
    ports:
      - "5432:5432"
    networks:
      - pg_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"
    networks:
      - pg_net
    depends_on:
      - pgdb

networks:
  pg_net:
    driver: bridge

volumes:
  pgadmin_data: